# Project Statement - 

Choose a real-world phenomenon that can be measured and for which you could
collect at least one-hundred data points across at least four different variables.

1) Investigate the types of variables involved, their likely distributions, and their
relationships with each other.

2) Synthesise/simulate a data set as closely matching their properties as possible.

3) Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook.


Note that this project is about simulation – you must synthesise a data set. Some
students may already have some real-world data sets in their own files. It is okay to
base your synthesised data set on these should you wish (please reference it if you do),
but the main task in this project is to create a synthesised data set. The next section
gives an example project idea.

In [5]:
# Importing of packages required for visualisations and to view within the notebook

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Prints the data set for review before visualisation

stats = pd.read_csv('https://raw.githubusercontent.com/ShaunaB93/Programming-for-Data-Analytics-Project/master/Data%20files/Stats%20file.csv')
#print(stats)
stats.head()

,Rank,Player,Height (cm),Minutes played 17/18,Headed Goals Scored 17/18,Goals Scored 17/18,Minutes played 16/17,Headed Goals Scored 16/17,Goals Scored 16/17,Minutes played 15/16,Headed Goals Scored 15/16,Goals Scored 15/16,Minutes played 14/15,Headed Goals Scored 14/15,Goals Scored 14/15,Total Headed Goals Scored,Total Goals Scored,Total Minutes Played
0,1.0,Jamie Vardy,179.0,3255.0,3.0,20.0,2808.0,0.0,13.0,3139.0,2.0,24.0,2245.0,0.0,5.0,5.0,62.0,11447.0
1,2.0,Harry Kane,188.0,3083.0,6.0,30.0,2531.0,2.0,29.0,3368.0,1.0,25.0,2581.0,5.0,21.0,14.0,105.0,11563.0
2,3.0,Xherdan Shaqiri,169.0,3049.0,0.0,8.0,1707.0,0.0,4.0,2028.0,0.0,3.0,0.0,0.0,0.0,0.0,15.0,6784.0
3,4.0,Mohamed Salah,175.0,2921.0,2.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,2.0,32.0,2951.0
4,5.0,Romelu Lukaku,190.0,2869.0,3.0,16.0,3267.0,6.0,25.0,3174.0,4.0,18.0,2875.0,1.0,10.0,14.0,69.0,12185.0